# Generated by Django 3.2.16 on 2024-12-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20241217_2149'),
        ('online', '0002_auto_20241217_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinerec',
            name='manicure_service',
        ),
        migrations.RemoveField(
            model_name='onlinerec',
            name='pedicure_service',
        ),
        migrations.AddField(
            model_name='onlinerec',
            name='manicure_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service_type': 'manicure'}, related_name='online_records', to='pages.PriceList', verbose_name='Услуги маникюра'),
        ),
        migrations.AddField(
            model_name='onlinerec',
            name='pedicure_services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service_type': 'pedicure'}, related_name='online_records', to='pages.PriceList1', verbose_name='Услуги педикюра'),
        ),
    ]
