# Generated by Django 3.2.16 on 2024-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20241219_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerec',
            name='service_type',
            field=models.CharField(choices=[('manicure', 'Маникюр'), ('pedicure', 'Педикюр'), ('manicure&pedicure', 'Маникюр и педикюр')], default='manicure', max_length=20, verbose_name='Тип услуги'),
        ),
    ]
