# Generated by Django 3.2.16 on 2024-12-20 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_onlinerec_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerec',
            name='appointment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата проведения услуги'),
        ),
    ]
