# Generated by Django 3.2.16 on 2024-12-20 16:10

from django.db import migrations, models
import online.validators


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_alter_onlinerec_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerec',
            name='appointment_time',
            field=models.TimeField(blank=True, default=None, null=True, validators=[online.validators.validate_appointment_time], verbose_name='Время проведения услуги'),
        ),
        migrations.AlterField(
            model_name='onlinerec',
            name='service_status',
            field=models.CharField(choices=[('created', 'Создана'), ('confirmed', 'Подтверждена'), ('postponed', 'Перенесена'), ('cancelled', 'Отменена'), ('completed', 'Выполнена')], default='created', max_length=20, verbose_name='Статус услуги'),
        ),
    ]
