# Generated by Django 3.2.16 on 2024-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app/', verbose_name='Фотографии работ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фотографии')),
            ],
            options={
                'verbose_name': 'фотографию работы',
                'verbose_name_plural': 'Фотографии работ',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=20, verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'услугу',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
    ]
