# Generated by Django 3.2.16 on 2024-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст совета')),
            ],
            options={
                'verbose_name': 'совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('-pub_date',), 'verbose_name': 'фотография работы', 'verbose_name_plural': 'Фотографии работ'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'прайс-лист', 'verbose_name_plural': 'Прайс-лист'},
        ),
    ]
