# Generated by Django 3.2.16 on 2024-09-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240920_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Заголовок совета'),
            preserve_default=False,
        ),
    ]
