# Generated by Django 3.2.16 on 2024-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=20, verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'прайс-лист',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('id',), 'verbose_name': 'прайс-лист', 'verbose_name_plural': 'Прайс-лист'},
        ),
    ]
