# Generated by Django 3.2.16 on 2024-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20241217_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='service_type',
            field=models.CharField(default='manicure', max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='pricelist1',
            name='service_type',
            field=models.CharField(default='pedicure', max_length=20, verbose_name='Тип услуги'),
        ),
    ]
