# Generated by Django 3.2.16 on 2025-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20241220_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='service',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='pricelist1',
            name='service',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название услуги'),
        ),
    ]
