# Generated by Django 3.2.16 on 2025-02-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20250113_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-id',), 'verbose_name': 'совет', 'verbose_name_plural': 'Советы'},
        ),
    ]
